# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest 2021 - GDG Santiago de Compostela"
email: "gdgsantiagodecompostela@gmail.com"
description: ""
baseurl: "/devfest"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Santiago"
organizerAlternateName: "Google Developer Group Santiago"
organizerDescription: "Google Developer Group de Santiago de Compostela. Organización sen ánimo de lucro para compartir coñecemento e xerar comunidade."
organizerEmail: "gdgsantiagodecompostela@gmail.com"
organizerLogo: "/img/seo/logoCadradoArriba.png"
organizerLink: "https://gdg.community.dev/gdg-santiago/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/YeoP2Dm5Yg8RzKAJ8"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Axenda"}
 - {permalink: "/speakers/", text: "Poñentes"}
 - {permalink: "/team/", text: "Equipo"}
 #- {permalink: "/logistics/", text: "Loxística"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/YeoP2Dm5Yg8RzKAJ8", text: "Ser poñente"}
rightNavigationButtons:
 - {link: "https://forms.gle/YeoP2Dm5Yg8RzKAJ8", text: "Ser poñente"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2021"
eventDate: "Outubro - Decembro, 2021"
typeoutTextValues: '"", "Connect", "Santiago de Compostela"'
typeoutFallback: "Connect"
heroButtons:
 - {id: "becomeSpeaker", link: "https://forms.gle/YeoP2Dm5Yg8RzKAJ8", text: "Ser poñente"}
 - {id: "buyTickets", link: "https://gdg.community.dev/events/details/google-gdg-santiago-presents-devfest-connect-introduccion-a-modelos-bayesianos-con-numpyro/", text: "Inscríbete gratis"}
buyTicketsTooltipText: "Os eventos sairán proximamente!"

# About Block
aboutTitle: "Sobre o GDG DevFest"
aboutBio: "Os Google Developer Groups (GDG) Dev Fest son eventos a grande escala dirixidos por e para a comunidade. Estes
eventos son celebrados anualmente por todo o mundo, habitualmente entre os meses de outubro e decembro.

Debido ao COVID-19 e ás limitacións existentes actualmente, dende o GDG Santiago queremos ofrecer un formato un tanto
diferente. Este ano o noso Dev Fest non consistirá nun evento único, presencial e multitudinario. A nosa proposta
baséase na realización de varios eventos en formato online ao longo dos meses de outubro, novembro e decembro con
poñentes e contidos incribles que esperamos que sexan do voso agrado."

aboutBlock:
 - {title: "Charlas", image: "microphone.png", text: "Charlas sobre tecnoloxía ou temáticas relacionadas co sector,
 interactivas, amenas e para todos os públicos." }
 - {title: "Talleres", image: "training.png", text: "Talleres onde poderás poñerte mans á obra no teu propio PC
 de forma guiada e dinámica." }


underConstructionImage: "hero.jpg"
underConstructionTitle: "En construción<typeout>"
underConstructionValues: '"...", ", amodiño"'
underConstructionFallback: ", amodiño"

# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
# - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Últimas novas"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 1
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
#locationBlockTitle: "Location"
#eventLocationName: "Conference Hall"
#eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
#eventStreetAddress: "22 Teatral'na St"
#eventAddressLocality: "Lviv"
#eventAddressLocalityRegion: "Lvivska"
#eventPostalCode: "79000"
#eventAddressCountry: "Ukraine"
#eventStartTime: "2014-10-25T10:00"
#eventDoorTime: "09:00"
#eventEndTime: "2014-10-25T20:00"
#eventPlaceCoordinates: "49.843237, 24.028751"
#mapCenterCoordinates: "49.842537, 24.025701"
#mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "E logo?"
twitterHashTag: "devfestsantiago"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000" #TODO: ??

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Quero ser patrocinador!"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/gdgsantiago/", icon: "linkedin"}
 - {link: "https://github.com/gdgsantiagoes", icon: "github"}
 - {link: "https://twitter.com/GDGSantiagoES", icon: "twitter"}
 - {link: "https://facebook.com/GDGSantiagoES", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"} #TODO: delete it?
footerBlocks:
 -
  title: "Ligazóns"
  links:
   - {link: "https://gdg.community.dev/gdg-santiago/", text: "GDG Community Dev: GDG Santiago"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gdgsantiagodecompostela@gmail.com", text: "gdgsantiagodecompostela@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conduta"}

# Blog
blogTitle: "Últimas novas"
blogCommentsEnabled: false
discusShortName: "devfestsantiago"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Google Developers Group (GDG) Santiago é unha organización sen ánimo de lucro patrocinada por Google e vinculada coa cidade de Santiago de Compostela. O obxectivo da organización non é outro que o de crear e fomentar unha comunidade tech na zona
á par que propor actividades para compartir coñecemento."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
